spring.application.name=backend-app
spring.datasource.url=${DB_URL:jdbc:h2:file:./data/poketeamdb}
spring.datasource.username=${DB_USERNAME:sa}
spring.datasource.password=${DB_PASSWORD:}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.h2.console.enabled=${H2_CONSOLE_ENABLED:false}
spring.h2.console.path=/h2-console
server.port=${PORT:8080}
app.cors.allowed-origins=${CORS_ALLOWED_ORIGINS:http://localhost:3000,https://web-poketeam.vercel.app,https://web-poketeam-*.vercel.app,https://web-poketeam-*-leo-chaves-projects-17c61e9e.vercel.app}
app.auth.token-days-valid=${AUTH_TOKEN_DAYS_VALID:7}
